version: '3.9'
services:
  yt-live-downloader:
    container_name: yt-live-downloader
    restart: unless-stopped
    # Optional: Set username to match user permissions on mounted volumes
    #user: "123:123"
    image: dalgibbard/yt-live-downloader:latest
    ports:
    - 5000:5000
# Optional:
#    environment:
#    - USERNAME=myuser
#    - PASSWORD=mysercretpassword